[package]
name = "stardust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
askama = { version = "0.14", features = ["serde_json"] }
axum = { version = "0.8", features = ["macros"] }
axum-template = "3.0.0"
deadpool-postgres = { version = "0.14", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
